stages:
  - lint
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|main)$/
    - if: $FORCE_DEPLOY
      when: always
    - when: never

variables:
  IMAGE_NAME: $ci_registry/$CI_PROJECT_PATH

default:
  before_script:
    - IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

lint_helm:
  stage: lint
  image: matthiasgabathuler/my-runner:ubuntu-20.04
  script:
    - >-
      helm lint ${CI_PROJECT_DIR}/helm
      --set image.name=${IMAGE_NAME}
      --set image.tag=${CI_COMMIT_REF_NAME}
      --set build.job_id=${CI_JOB_ID}
      --set build.commit=${CI_COMMIT_SHA}

build_webapp:
  stage: build
  rules:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${IMAGE_NAME}-webapp:latest"

install_webscraping_dependencies:
  stage: build
  image: python:3.11
  script:
    - sudo apt update
    - sudo apt install -y python3-pip wget
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - sudo dpkg -i google-chrome-stable_current_amd64.deb
    - sudo apt-get install -f
    - google-chrome --version
    - CHROME_VERSION=$(google-chrome --version | grep -oP "(?<=Google Chrome )[\d\.]+")
    - CHROMEDRIVER_VERSION=$(echo $CHROME_VERSION | cut -d'.' -f1)
    - wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION.0.4515.107/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo mv chromedriver /usr/bin/chromedriver
    - sudo chown root:root /usr/bin/chromedriver
    - sudo chmod +x /usr/bin/chromedriver
    - pip install -r requirements.txt
    - chromedriver --url-base=/wd/hub
  artifacts:
    paths:
      - .

deploy_app:
  stage: deploy
  rules:
  image:
    name: alpine/helm:3.11.1
    entrypoint: [""]
  script:
    - >-
      helm --namespace $k8s_namespace
      --kube-context $k8s_context
      upgrade $(echo ${CI_PROJECT_NAME} | tr _ -) ${CI_PROJECT_DIR}/helm
      --install
      --history-max 5
      --set image.host=${ci_registry}
      --set image.name=${IMAGE_NAME}
      --set image.tag=latest
      --set build.job_id=${CI_JOB_ID}
      --set build.commit=${CI_COMMIT_SHA}
    - >-
      echo "webapp URL: http://$(echo ${CI_PROJECT_NAME} | tr _ -).course-fwe-2023.isginf.ch"
